const QUESTIONS = [
  { level: 1, text: "Você esconde algo vergonhoso da mesa? O quê?" },
  { level: 1, text: "Qual foi sua última mentirinha social aqui?" },
  { level: 1, text: "Qual hábito seu você sabe que irrita alguém da roda?" },
  { level: 1, text: "O que você apagaria do seu histórico sem pensar?" },
  { level: 1, text: "Qual apelido que você detesta mas já aceitou?" },
  { level: 1, text: "Qual seu mico mais recente?" },
  { level: 1, text: "Uma qualidade que você às vezes finge ter?" },
  { level: 1, text: "Quem aqui você evita quando está sem paciência? (pode dizer {{outro}})" },
  { level: 1, text: "O que você procrastinou hoje?" },
  { level: 1, text: "Qual mania sua ninguém sabe?" },
  { level: 1, text: "Qual sua opinião impopular sobre comida?" },
  { level: 1, text: "Qual sua vergonha secreta de infância?" },
  { level: 1, text: "Um medo bobo que você tem até hoje?" },
  { level: 1, text: "Qual trend que você seguiu e se arrependeu?" },
  { level: 1, text: "Qual compra por impulso recente que não precisava?" },
  { level: 1, text: "Qual hábito estranho quando está sozinho(a)?" },
  { level: 1, text: "Complete: “Eu fico insuportável quando…”" },
  { level: 1, text: "Qual mensagem não respondida que você está evitando?" },
  { level: 1, text: "Quando foi a última vez que chorou de raiva?" },
  { level: 1, text: "Quem da mesa te intimida um pouquinho?" },
  { level: 1, text: "Uma série/filme que você ama mas tem vergonha de admitir?" },
  { level: 1, text: "Uma música que você escuta escondido?" },
  { level: 1, text: "Qual app te rouba tempo sem você notar?" },
  { level: 1, text: "Você já stalkeou alguém da mesa? Quem? ({{outro}} ou passe)" },
  { level: 1, text: "Qual rumor sobre você que é verdade?" },
  { level: 1, text: "Qual rumor sobre você que é mentira?" },
  { level: 1, text: "Qual hábito higiênico você gostaria de melhorar?" },
  { level: 1, text: "Qual hábito financeiro vergonhoso?" },
  { level: 1, text: "Qual comida que você gosta e todos acham estranha?" },
  { level: 1, text: "Qual habilidade que você finge entender?" },
  { level: 1, text: "Qual mensagem que você digitou e não enviou?" },
  { level: 1, text: "O que te irrita instantaneamente numa conversa?" },
  { level: 1, text: "O que você coleciona secretamente?" },
  { level: 1, text: "Sua pior fase de estilo foi qual?" },
  { level: 1, text: "Um crush improvável seu (pode ser famoso)." },
  { level: 1, text: "Quem da mesa você já subestimou?" },
  { level: 1, text: "Quando foi a última vez que chegou atrasado e mentiu o motivo?" },
  { level: 1, text: "Sua maior gafe em rede social?" },
  { level: 1, text: "Qual palavra você sempre fala errado?" },
  { level: 1, text: "Qual comida você odeia e às vezes finge que gosta?" },
  { level: 1, text: "Seu último sonho bizarro?" },
  { level: 1, text: "Qual tarefa doméstica você foge?" },
  { level: 1, text: "Qual mensagem fixada da mesa você nunca leu?" },
  { level: 1, text: "Quem da mesa você silenciaria por um dia?" },
  { level: 1, text: "O que te dá vergonha alheia garantida?" },
  { level: 1, text: "Sua última pesquisa esquisita?" },
  { level: 1, text: "Qual app você esconderia da tela inicial?" },
  { level: 1, text: "Qual roupa você repete demais?" },
  { level: 1, text: "Qual dia da semana você rende menos e por quê?" },
  { level: 1, text: "Qual hábito de beleza você pula?" },
  { level: 1, text: "Qual apelido secreto que você deu pra alguém?" },
  { level: 1, text: "Qual desculpa que você usa com mais frequência?" },
  { level: 1, text: "Quando foi a última vez que você sumiu do nada?" },
  { level: 1, text: "Qual mania de organização você não tem?" },
  { level: 1, text: "Qual emoji você usa errado?" },
  { level: 1, text: "Qual expressão você detesta ouvir?" },
  { level: 1, text: "Qual mania de mesa te irrita?" },
  { level: 1, text: "Qual história você conta exagerando?" },
  { level: 1, text: "Qual app você já desinstalou e voltou?" },
  { level: 1, text: "Qual item você sempre esquece de comprar?" },
  { level: 1, text: "Qual hábito de saúde você finge seguir?" },
  { level: 1, text: "Sua última “segunda eu começo”?" },
  { level: 1, text: "Qual trend de dança você tentou?" },
  { level: 1, text: "Quem da mesa você deixa no vácuo às vezes?" },
  { level: 1, text: "Em que situação você paga de entendido e não é?" },
  { level: 1, text: "Qual mania de correção (gramática) você tem?" },
  { level: 1, text: "Qual seu último arrependimento culinário?" },
  { level: 1, text: "Quando foi a última vez que você tentou se reconciliar?" },
  { level: 1, text: "Qual tabu bobo que você ainda tem?" },
  { level: 1, text: "Qual a coisa mais cringe que você já postou?" },
  { level: 1, text: "Passe sua vez para outra pessoa" },
  { level: 1, text: "Passe sua vez para {{outro}}" },
  { level: 1, text: "Pague a prenda" },
  { level: 2, text: "Você já ignorou uma mensagem de {{outro}} de propósito?" },
  { level: 2, text: "Você já riu de {{outro}} escondido?" },
  { level: 2, text: "Você já ficou irritado(a) com o jeito de {{outro}}?" },
  { level: 2, text: "Você já achou que {{outro}} força demais nas piadas?" },
  { level: 2, text: "Você já evitou chamar {{outro}} para algum rolê?" },
  { level: 2, text: "Você já se arrependeu de confiar em {{outro}} com alguma tarefa?" },
  { level: 2, text: "Você já sentiu que {{outro}} só aparece quando convém?" },
  { level: 2, text: "Você já achou que {{outro}} se vitimiza?" },
  { level: 2, text: "Você já achou que {{outro}} dá opinião sem ser chamado?" },
  { level: 2, text: "Você já se sentiu interrompido(a) por {{outro}}?" },
  { level: 2, text: "Você já achou que {{outro}} exagera nas histórias?" },
  { level: 2, text: "Você já duvidou de um elogio que {{outro}} fez pra você?" },
  { level: 2, text: "Você já se incomodou com a mania de {{outro}}?" },
  { level: 2, text: "Você já achou que {{outro}} procura validação demais?" },
  { level: 2, text: "Você já quis silenciar {{outro}} por um tempo?" },
  { level: 2, text: "Quem aqui mais força um personagem?" },
  { level: 2, text: "Quem aqui some quando mais precisa?" },
  { level: 2, text: "Quem aqui tem o pior timing de piada?" },
  { level: 2, text: "Quem aqui puxa assunto só por interesse?" },
  { level: 2, text: "Quem aqui sempre exagera nas histórias?" },
  { level: 2, text: "Quem aqui mais interrompe os outros?" },
  { level: 2, text: "Quem aqui mais muda de opinião pelo grupo?" },
  { level: 2, text: "Quem aqui mais rende fofoca sem querer?" },
  { level: 2, text: "Quem aqui aparece só quando é conveniente?" },
  { level: 2, text: "Quem aqui mais promete e não cumpre?" },
  { level: 2, text: "Quem aqui perde a linha mais rápido?" },
  { level: 2, text: "Quem aqui se vitimiza com frequência?" },
  { level: 2, text: "Quem aqui critica mas nunca ajuda?" },
  { level: 2, text: "Quem aqui compete até em bobagens?" },
  { level: 2, text: "Quem aqui mais cobra presença mas não aparece?" },
  { level: 3, text: "Você já guardou um segredo de {{outro}}?" },
  { level: 3, text: "Você já mentiu para {{outro}} para não magoar?" },
  { level: 3, text: "Você já sentiu ciúmes de {{outro}}?" },
  { level: 3, text: "Você já se sentiu traído(a) por {{outro}}?" },
  { level: 3, text: "Você já desejou se afastar de {{outro}}?" },
  { level: 3, text: "Você já desconfiou de algo que {{outro}} falou?" },
  { level: 3, text: "Você já protegeu {{outro}} de uma fofoca?" },
  { level: 3, text: "Você já espalhou algo que {{outro}} te contou em segredo?" },
  { level: 3, text: "Você já se arrependeu de confiar em {{outro}}?" },
  { level: 3, text: "Você já se sentiu mais próximo(a) de {{outro}} do que deveria?" },
  { level: 3, text: "Você já fingiu apoiar {{outro}} sem acreditar?" },
  { level: 3, text: "Você já desejou que {{outro}} não estivesse no grupo?" },
  { level: 3, text: "Você já perdoou {{outro}} mas ainda guarda mágoa?" },
  { level: 3, text: "Você já se sentiu injustiçado(a) por {{outro}}?" },
  { level: 3, text: "Você já teve medo de contar algo para {{outro}}?" },
  { level: 3, text: "Quem aqui você não confiaria para guardar um segredo?" },
  { level: 3, text: "Quem aqui já te decepcionou de verdade?" },
  { level: 3, text: "Quem aqui você protegeria numa treta, mesmo errado(a)?" },
  { level: 3, text: "Quem aqui seria o primeiro a te expor sem querer?" },
  { level: 3, text: "Quem aqui você confiaria suas senhas?" },
  { level: 3, text: "Quem aqui tem fama injusta?" },
  { level: 3, text: "Quem aqui tem fama justa?" },
  { level: 3, text: "Quem aqui você pediria ajuda numa crise?" },
  { level: 3, text: "Quem aqui você acha que guarda rancor?" },
  { level: 3, text: "Quem aqui você acha que esquece rápido os erros?" },
  { level: 3, text: "Quem aqui mais espalharia uma fofoca?" },
  { level: 3, text: "Quem aqui você nunca emprestaria dinheiro?" },
  { level: 3, text: "Quem aqui você deixaria cuidar do seu pet?" },
  { level: 3, text: "Quem aqui você chamaria no meio da madrugada?" },
  { level: 3, text: "Quem aqui já te surpreendeu positivamente?" },
  { level: 3, text: "Quem aqui já te surpreendeu negativamente?" },
  { level: 4, text: "Quem aqui se acha mais bonito do que realmente é?" },
  { level: 4, text: "Quem aqui mais gosta de aparecer?" },
  { level: 4, text: "Quem aqui não aceita perder em nada?" },
  { level: 4, text: "Quem aqui é mais provável de postar só vitória nas redes?" },
  { level: 4, text: "Quem aqui gasta mais tempo no espelho?" },
  { level: 4, text: "Quem aqui mais julga o estilo dos outros?" },
  { level: 4, text: "Quem aqui faz questão de sempre estar na foto?" },
  { level: 4, text: "Quem aqui nunca aceita uma crítica numa boa?" },
  { level: 4, text: "Quem aqui gosta de ostentar?" },
  { level: 4, text: "Quem aqui já fingiu humildade?" },
  { level: 4, text: "Quem aqui tem o ego mais frágil?" },
  { level: 4, text: "Quem aqui já comprou algo só para impressionar?" },
  { level: 4, text: "Quem aqui sempre tenta ser o centro do rolê?" },
  { level: 4, text: "Quem aqui faria de tudo por likes?" },
  { level: 4, text: "Quem aqui já inventou história para parecer melhor?" },
  { level: 4, text: "Você já escondeu algo de {{outro}}?" },
  { level: 4, text: "Qual crítica você já pensou mas não falou para {{outro}}?" },
  { level: 4, text: "Qual elogio você nunca deu para {{outro}}?" },
  { level: 4, text: "Você já teve inveja de {{outro}}? Por quê?" },
  { level: 4, text: "Já quis trocar de vida com {{outro}} por um dia?" },
  { level: 4, text: "Você já julgou o estilo de {{outro}}?" },
  { level: 4, text: "Você já copiou algo de {{outro}}?" },
  { level: 4, text: "Você já se sentiu intimidado(a) pela aparência de {{outro}}?" },
  { level: 4, text: "Você já falou mal do look de {{outro}}?" },
  { level: 4, text: "Você já quis ter o corpo/cabelo de {{outro}}?" },
  { level: 4, text: "Você já exagerou um elogio para {{outro}}?" },
  { level: 4, text: "Você já riu de {{outro}} sem que ele(a) percebesse?" },
  { level: 4, text: "Já achou que {{outro}} força uma pose/persona?" },
  { level: 4, text: "Você já se comparou com {{outro}} e perdeu?" },
  { level: 4, text: "Você já se comparou com {{outro}} e ganhou?" },
  { level: 4, text: "Você já inventou uma desculpa para não sair com {{outro}}?" },
  { level: 4, text: "Você já ignorou mensagem de {{outro}}?" },
  { level: 4, text: "Você já fingiu gostar de algo que {{outro}} fez?" },
  { level: 4, text: "Você já se sentiu pressionado(a) por {{outro}}?" },
  { level: 4, text: "Você já desejou que {{outro}} se desse mal em algo?" },
  { level: 4, text: "Você já sentiu vergonha alheia de {{outro}}?" },
  { level: 4, text: "Você já se inspirou de verdade em {{outro}}?" },
  { level: 4, text: "Você já fingiu rir de piada de {{outro}}?" },
  { level: 4, text: "Qual mania de {{outro}} mais te irrita?" },
  { level: 4, text: "Qual mania de {{outro}} você secretamente admira?" },
  { level: 4, text: "Você já competiu com {{outro}} sem ele(a) saber?" },
  { level: 4, text: "Você já teve vontade de copiar o estilo de {{outro}}?" },
  { level: 4, text: "Você já criticou {{outro}} pelas costas?" },
  { level: 4, text: "Você já defendeu {{outro}} mesmo não concordando?" },
  { level: 4, text: "Você já desejou ter o carisma de {{outro}}?" },
  { level: 4, text: "Você já se arrependeu de algo que disse para {{outro}}?" },
  { level: 4, text: "Você já fingiu não ouvir {{outro}} de propósito?" },
  { level: 4, text: "Você já mentiu um elogio para {{outro}}?" },
  { level: 4, text: "Você já pensou 'ainda bem que não sou {{outro}}'?" },
  { level: 4, text: "Você já pensou 'queria ser mais como {{outro}}'?" },
  { level: 4, text: "Você já sentiu que {{outro}} tenta te superar?" },
  { level: 4, text: "Você já teve orgulho secreto de {{outro}}?" },
  { level: 5, text: "Qual segredo romântico você guarda de {{outro}}?" },
  { level: 5, text: "Você já sonhou em ficar com {{outro}}?" },
  { level: 5, text: "Você já teve ciúmes de {{outro}}?" },
  { level: 5, text: "Já sentiu tesão por {{outro}}?" },
  { level: 5, text: "Você já mentiu pra {{outro}} pra não magoar?" },
  { level: 5, text: "Qual conselho amoroso você daria para {{outro}}?" },
  { level: 5, text: "Se tivesse que beijar alguém agora, escolheria {{outro}}?" },
  { level: 5, text: "Qual a coisa mais fofa que {{outro}} já fez por você?" },
  { level: 5, text: "Você já escondeu uma ficada de {{outro}}?" },
  { level: 5, text: "Se {{outro}} estivesse solteiro(a), você tentaria algo?" },
  { level: 5, text: "Com quem da mesa você teria mais química num beijo?" },
  { level: 5, text: "E menos química?" },
  { level: 5, text: "Quem tem mais vibe de receber/enviar nudes?" },
  { level: 5, text: "Quem ficaria no 1º encontro com mais facilidade?" },
  { level: 5, text: "Quem é mais 'difícil'?" },
  { level: 5, text: "Um green flag seu nessa área?" },
  { level: 5, text: "Um red flag seu (sem detalhes)?" },
  { level: 5, text: "Qual mentira íntima você já contou?" },
  { level: 5, text: "Quem tem energia mais dominante?" },
  { level: 5, text: "Quem tem energia mais submissa?" },
  { level: 5, text: "Você toparia relacionamento aberto? Com qual regra?" },
  { level: 5, text: "O que te desliga na hora em situação íntima?" },
  { level: 5, text: "Qual elogio íntimo te ganha?" },
  { level: 5, text: "Qual comentário te faz perder o clima?" },
  { level: 5, text: "Já confundiu carinho com validação?" },
  { level: 5, text: "Já confundiu desejo com carência?" },
  { level: 5, text: "Quem mais flerta por esporte?" },
  { level: 5, text: "Quem confunde gentileza com flerte?" },
  { level: 5, text: "Quem manda sinal trocado?" },
  { level: 5, text: "Quem some depois de conseguir atenção?" },
  { level: 5, text: "Você já deu ghost após um encontro? Por quê?" },
  { level: 5, text: "Já levou ghost? Como lidou?" },
  { level: 5, text: "Você prefere falar claro ou deixar subentendido?" },
  { level: 5, text: "Qual limite inegociável seu?" },
  { level: 5, text: "Qual fantasia leve que você topa revelar?" },
  { level: 5, text: "Quem seria um bom par casual?" },
  { level: 5, text: "Quem seria um péssimo par?" },
  { level: 5, text: "Quem separa bem amizade e pegação?" },
  { level: 5, text: "Quem mistura tudo?" },
  { level: 5, text: "Você já misturou amizade e pegação? Como foi?" },
  { level: 5, text: "Você contaria para a mesa se ficasse com alguém daqui?" },
  { level: 5, text: "Você já teve crush em {{outro}}?" },
  { level: 5, text: "Quem tem mais cara de 'não responde depois'?" },
  { level: 5, text: "Quem tem mais cara de 'apaixona rápido'?" },
  { level: 5, text: "Quem tem mais cara de 'fica e some'?" },
  { level: 5, text: "Quem tem padrão de pessoas parecido com o seu?" },
  { level: 5, text: "Quem mais pede validação romântica?" },
  { level: 5, text: "Quem dispensa do jeito mais gentil?" },
  { level: 5, text: "E do jeito mais frio?" },
  { level: 5, text: "Seu maior erro num primeiro encontro?" },
  { level: 5, text: "Seu maior acerto?" },
  { level: 5, text: "Você prefere iniciativa ou ser procurado(a)?" },
  { level: 5, text: "Você avisa quando perde o interesse?" },
  { level: 5, text: "Já foi desonesto(a) pra não magoar?" },
  { level: 5, text: "O que te faz perder o interesse mesmo com química?" },
  { level: 5, text: "O que te mantém interessado(a) mesmo com pouca química?" },
  { level: 5, text: "Você toparia ficar com alguém da mesa se não tivesse consequência?" },
  { level: 5, text: "Quem? (pode passar)" },
  { level: 5, text: "Você manteria segredo sobre ficar com alguém daqui?" },
  { level: 5, text: "Você já espalhou algo íntimo de alguém? Como reparou?" },
  { level: 5, text: "Já te expuseram? Como você lidou?" },
  { level: 5, text: "Você lida bem com 'só amigos'?" },
  { level: 5, text: "Você já ficou por tédio?" },
  { level: 5, text: "Já ficou por status?" },
  { level: 5, text: "Se {{outro}} quisesse a mesma pessoa que você, o que faria?" },
  { level: 5, text: "Você dividiria seus sentimentos com {{outro}}?" },
  { level: 5, text: "Você beijaria {{outro}} num jogo? Por quê?" },
  { level: 5, text: "Qual segredo romântico você guardou de alguém aqui?" },
  { level: 5, text: "Que conselho amoroso você daria para {{outro}}?" },
  { level: 5, text: "O que seria um encontro perfeito pra você (sem detalhes íntimos)?" },
  { level: 5, text: "Qual música combina com sua vibe romântica?" },
  { level: 5, text: "Qual sinal de alerta você ignora?" },
  { level: 5, text: "Qual sinal de alerta você percebe de longe?" },
  { level: 6, text: "Você daria pra alguém da mesa? Quem?" },
  { level: 6, text: "Qual sua posição favorita no sexo?" },
  { level: 6, text: "Se tivesse que matar alguém aqui, quem seria?" },
  { level: 6, text: "Quem da mesa você acha que teria mais chance de se drogar?" },
  { level: 6, text: "Você já transou sem camisinha? Se arrependeu?" },
  { level: 6, text: "Qual foi o lugar mais improvável onde já transou?" },
  { level: 6, text: "Quem da mesa você acha que transa pior?" },
  { level: 6, text: "Quem da mesa você acha que transa melhor?" },
  { level: 6, text: "Qual sua maior fantasia sexual não realizada?" },
  { level: 6, text: "Você já traiu alguém? Como foi?" },
  { level: 6, text: "Você já foi amante de alguém comprometido?" },
  { level: 6, text: "Se pudesse ficar com dois da mesa ao mesmo tempo, quem seriam?" },
  { level: 6, text: "Qual foi sua pior experiência sexual?" },
  { level: 6, text: "Você já broxou ou fez alguém broxar? Conta." },
  { level: 6, text: "Qual foi a coisa mais ilegal que você já fez?" },
  { level: 6, text: "Quem da mesa você acha que acabaria preso primeiro?" },
  { level: 6, text: "Você toparia gravar uma sextape? Com quem da mesa?" },
  { level: 6, text: "Você já mandou ou recebeu nudes vazados sem consentimento?" },
  { level: 6, text: "Qual droga você teria curiosidade de experimentar?" },
  { level: 6, text: "Quem da mesa você acha que já transou em público?" },
  { level: 6, text: "Você já fez sexo por interesse? (dinheiro, status, favor…)" },
  { level: 6, text: "Você já pensou em se vingar de alguém? Como?" },
  { level: 6, text: "Quem da mesa você deixaria morrer para se salvar?" },
  { level: 6, text: "Você toparia um ménage com alguém daqui? Quem?" },
  { level: 6, text: "Qual foi a vez que você mais se arrependeu no sexo?" },
  { level: 6, text: "Você já sentiu tesão por alguém da família distante?" },
  { level: 6, text: "Você já roubou algo de valor? O quê?" },
  { level: 6, text: "Se tivesse que escolher alguém daqui pra torturar, quem seria?" },
  { level: 6, text: "Você toparia vender fotos íntimas se ninguém descobrisse?" },
  { level: 6, text: "Você já pensou em trair mas não fez? Com quem?" },
  { level: 6, text: "Quem da mesa você acha que teria coragem de matar?" },
  { level: 6, text: "Qual foi o segredo mais obscuro que já guardou?" },
  { level: 6, text: "Você já desejou o parceiro(a) de um amigo(a)?" },
  { level: 6, text: "Você já usou sexo como forma de manipulação?" },
  { level: 6, text: "Qual é o fetiche mais estranho que você já teve?" },
  { level: 6, text: "Quem da mesa você acha que toparia fazer pornô?" },
  { level: 6, text: "Você já pensou em se drogar pesado só pela experiência?" },
  { level: 6, text: "Você já se envolveu em briga física séria? Como foi?" },
  { level: 6, text: "Você toparia trair se tivesse certeza que nunca seria descoberto?" },
  { level: 6, text: "Quem da mesa você acha que faria sexo por dinheiro?" },
  { level: 6, text: "Qual foi o maior segredo sujo que já te contaram?" },
  { level: 6, text: "Você já fez algo que poderia dar cadeia?" },
  { level: 6, text: "Quem da mesa você acha que já usou droga pesada?" },
  { level: 6, text: "Se tivesse que expor um podre de alguém aqui, de quem seria?" },
  // 🔹 Nível 1 – bobos, engraçados, leves
  { level: 1, text: "Passe sua vez para outra pessoa" },
  { level: 1, text: "Passe sua vez para {{outro}}" },
  { level: 1, text: "Pague a prenda" },
  { level: 1, text: "Dance por 10 segundos no meio da roda" },
  { level: 1, text: "Faça uma careta até alguém rir" },
  { level: 1, text: "Imite um animal até alguém adivinhar" },
  { level: 1, text: "Fale uma frase em voz de bebê" },
  { level: 1, text: "Cante um trecho de música bem alto" },
  { level: 1, text: "Faça polichinelo até contarem 10" },
  { level: 1, text: "Dê um abraço coletivo na galera" },

  // 🔹 Nível 2 – constrangimento leve, interações divertidas
  { level: 2, text: "Passe sua vez para outra pessoa" },
  { level: 2, text: "Passe sua vez para {{outro}}" },
  { level: 2, text: "Pague a prenda" },
  { level: 2, text: "Imite {{outro}} por 10 segundos" },
  { level: 2, text: "Diga algo fofo para {{outro}}" },
  { level: 2, text: "Deixe {{outro}} escolher sua próxima ação" },
  { level: 2, text: "Dance colado(a) com {{outro}} por 5s" },
  { level: 2, text: "Cante olhando nos olhos de {{outro}}" },
  { level: 2, text: "Fale uma qualidade de {{outro}} em voz alta" },
  { level: 2, text: "Fique de mãos dadas com {{outro}} até o fim da rodada" },

  // 🔹 Nível 3 – segredos leves + ações de proximidade
  { level: 3, text: "Passe sua vez para outra pessoa" },
  { level: 3, text: "Passe sua vez para {{outro}}" },
  { level: 3, text: "Pague a prenda" },
  { level: 3, text: "Sussurre uma frase no ouvido de {{outro}}" },
  { level: 3, text: "Olhe nos olhos de {{outro}} por 15 segundos sem rir" },
  { level: 3, text: "Faça cócegas em {{outro}}" },
  { level: 3, text: "Deixe {{outro}} fazer uma pergunta e responda sem recusar" },
  { level: 3, text: "Deixe {{outro}} mexer no seu cabelo" },
  { level: 3, text: "Diga em voz alta: 'eu confio em {{outro}}'" },
  { level: 3, text: "Troque de lugar com {{outro}} até a próxima rodada" },

  // 🔹 Nível 4 – vaidade, exposição, charme
  { level: 4, text: "Passe sua vez para outra pessoa" },
  { level: 4, text: "Passe sua vez para {{outro}}" },
  { level: 4, text: "Pague a prenda" },
  { level: 4, text: "Dance sensual por 5 segundos" },
  { level: 4, text: "Faça uma pose como se fosse modelo" },
  { level: 4, text: "Deixe {{outro}} tirar uma foto sua agora" },
  { level: 4, text: "Diga 'eu sou mais bonito(a) que {{outro}}' em voz alta" },
  { level: 4, text: "Dê uma volta fingindo que está em passarela" },
  { level: 4, text: "Deixe {{outro}} escolher uma música para você rebolar" },
  { level: 4, text: "Faça uma declaração falsa de amor para {{outro}}" },

  // 🔹 Nível 5 – romance, clima, intimidade leve
  { level: 5, text: "Passe sua vez para outra pessoa" },
  { level: 5, text: "Passe sua vez para {{outro}}" },
  { level: 5, text: "Pague a prenda" },
  { level: 5, text: "Beije alguém no rosto" },
  { level: 5, text: "Beije a mão de {{outro}}" },
  { level: 5, text: "Dê um abraço apertado em {{outro}}" },
  { level: 5, text: "Dance colado(a) com alguém" },
  { level: 5, text: "Declare 'eu tenho um crush em {{outro}}' (mesmo que seja zoeira)" },
  { level: 5, text: "Encoste testa com testa em {{outro}} e fique 5s" },
  { level: 5, text: "Segure na cintura de {{outro}} até a rodada acabar" },

  // 🔹 Nível 6 – pesadão, picante e ousado
  { level: 6, text: "Passe sua vez para outra pessoa" },
  { level: 6, text: "Passe sua vez para {{outro}}" },
  { level: 6, text: "Pague a prenda" },
  { level: 6, text: "Beije alguém na boca" },
  { level: 6, text: "Dê um selinho em {{outro}}" },
  { level: 6, text: "Sente no colo de {{outro}} por 10s" },
  { level: 6, text: "Dê um beijo no pescoço de {{outro}}" },
  { level: 6, text: "Dance de forma provocante para {{outro}}" },
  { level: 6, text: "Beije 2 pessoas diferentes da mesa" },
  { level: 6, text: "Sussurre algo quente no ouvido de {{outro}}" },
  
  // 🔥 Level 7 – Perguntas Sem Vergonha (18+)
  { level: "7", text: "Tire uma peça de roupa" },
  { level: "7", text: "Dê um beijo de língua em {{outro}}" },
  { level: "7", text: "Sente no colo de {{outro}} até a rodada acabar" },
  { level: "7", text: "Beije 3 pessoas diferentes da mesa" },
  { level: "7", text: "Deixe {{outro}} escolher alguém para você beijar" },
  { level: "7", text: "Dance de forma provocante até todos aplaudirem" },
  { level: "7", text: "Dê um chupão no pescoço de {{outro}}" },
  { level: "7", text: "Tire uma peça de roupa de {{outro}}" },
  { level: "7", text: "Deixe {{outro}} dar um tapa na sua bunda" },
  { level: "7", text: "Troque de camiseta com {{outro}} agora" },
  { level: "7", text: "Beije o corpo de {{outro}} em qualquer lugar (exceto boca)" },
  { level: "7", text: "Deixe {{outro}} passar a mão no seu cabelo e pescoço" },
  { level: "7", text: "Faça uma dança no colo de {{outro}}" },
  { level: "7", text: "Deixe alguém aqui tirar uma peça da sua roupa" },
  { level: "7", text: "Encoste corpo com corpo em {{outro}} por 10s" },
  { level: "7", text: "Beije a barriga ou o ombro de {{outro}}" },
  { level: "7", text: "Deixe {{outro}} escolher uma parte sua para beijar" },
  { level: "7", text: "Finja que vai dar um amasso em {{outro}} por 10s" },
  { level: "7", text: "Dance rebolando encostado em {{outro}}" },
  { level: "7", text: "Mostre algo íntimo (pode ser só zoeira, mas tem que convencer)" },
  { level: "7", text: "Qual parte do corpo você mais gosta que toquem?" },
  { level: "7", text: "Qual parte do seu corpo você acha mais sexy?" },
  { level: "7", text: "Quem da mesa você gostaria de ver sem roupa?" },
  { level: "7", text: "Você já se tocou pensando em {{outro}}?" },
  { level: "7", text: "Qual foi o lugar mais estranho onde você já transou?" },
  { level: "7", text: "Você já gravou ou toparia gravar uma sextape?" },
  { level: "7", text: "Qual foi a última vez que você ficou nu(a) na frente de alguém?" },
  { level: "7", text: "Você já mandou nude para {{outro}} ou já pensou em mandar?" },
  { level: "7", text: "Quem da mesa você acha que beija melhor?" },
  { level: "7", text: "Quem da mesa você beijaria agora sem pensar?" },
  { level: "7", text: "Qual foi sua maior loucura sexual até hoje?" },
  { level: "7", text: "Você já transou em lugar público? Onde?" },
  { level: "7", text: "Qual sua posição favorita no sexo?" },
  { level: "7", text: "Quem da mesa você toparia passar uma noite inteira?" },
  { level: "7", text: "Você já fez sexo sem camisinha?" },
  { level: "7", text: "Você já ficou com duas pessoas no mesmo dia?" },
  { level: "7", text: "Você já fantasiou com alguém comprometido?" },
  { level: "7", text: "Você já usou brinquedo erótico?" },
  { level: "7", text: "Qual foi a coisa mais proibida que já fez na cama?" },
  { level: "7", text: "Se tivesse que escolher alguém da mesa pra banho juntos, quem seria?" },
  // Corpo e desejo
  { level: "7", text: "Qual parte do corpo você mais gosta que toquem?" },
  { level: "7", text: "Qual parte do seu corpo você acha mais sexy?" },
  { level: "7", text: "Qual parte do corpo de {{outro}} você mais reparou?" },
  { level: "7", text: "Você já se tocou pensando em {{outro}}?" },
  { level: "7", text: "Se tivesse que beijar uma parte do corpo de {{outro}}, qual seria?" },
  { level: "7", text: "Qual parte do corpo você esconderia se estivesse sem roupa agora?" },

  // Beijo, pegação
  { level: "7", text: "Quem da mesa você beijaria agora sem pensar?" },
  { level: "7", text: "Quem da mesa você acha que beija melhor?" },
  { level: "7", text: "Quem da mesa você toparia passar uma noite inteira?" },
  { level: "7", text: "Você já beijou mais de uma pessoa no mesmo rolê?" },
  { level: "7", text: "Você já ficou com alguém só por desejo físico?" },

  // Sexo e intimidade
  { level: "7", text: "Qual sua posição favorita no sexo?" },
  { level: "7", text: "Qual foi sua maior loucura sexual até hoje?" },
  { level: "7", text: "Você já transou em lugar público? Onde?" },
  { level: "7", text: "Você já transou sem camisinha?" },
  { level: "7", text: "Você já ficou com duas pessoas no mesmo dia?" },
  { level: "7", text: "Você já transou com mais de uma pessoa ao mesmo tempo?" },
  { level: "7", text: "Você já gravou ou toparia gravar uma sextape?" },
  { level: "7", text: "Você já mandou nudes para {{outro}} ou já pensou em mandar?" },

  // Fantasias e desejos
  { level: "7", text: "Qual é sua maior fantasia sexual não realizada?" },
  { level: "7", text: "Você já fantasiou com alguém da mesa? Quem?" },
  { level: "7", text: "Você já fantasiou com alguém comprometido?" },
  { level: "7", text: "Você toparia um ménage? Com quem da mesa?" },
  { level: "7", text: "Você já desejou dormir com alguém proibido?" },
  { level: "7", text: "Você toparia sexo sem compromisso hoje?" },

  // Experiências proibidas
  { level: "7", text: "Você já usou brinquedo erótico?" },
  { level: "7", text: "Você já pagou ou recebeu por sexo?" },
  { level: "7", text: "Você já ficou com alguém muito mais velho(a)?" },
  { level: "7", text: "Você já ficou com alguém muito mais novo(a)?" },
  { level: "7", text: "Qual foi a coisa mais proibida que já fez na cama?" },
  { level: "7", text: "Você já traiu só por tesão?" },

  // Mais ousadas
  { level: "7", text: "Você já ficou nu(a) na frente de amigos?" },
  { level: "7", text: "Você já foi pego(a) no flagra transando?" },
  { level: "7", text: "Você já experimentou algo que te chocou no sexo?" },
  { level: "7", text: "Quem da mesa você levaria pro banheiro agora?" },
  { level: "7", text: "Se tivesse que dormir com alguém da mesa hoje, quem seria?" },
  { level: "7", text: "Você já usou sexo para conseguir algo?" },
  { level: "7", text: "Você já desejou alguém do mesmo sexo que você?" },
  { level: "7", text: "Você já ficou com alguém e se arrependeu logo depois?" },
  { level: "7", text: "Qual foi a vez que você mais perdeu o controle do desejo?" },
];

export default QUESTIONS;
